# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .policy import *
from .provider import *
from .role import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-iam",
  "mod": "index",
  "fqn": "pulumi_aws_iam",
  "classes": {
   "aws-iam:index:Policy": "Policy",
   "aws-iam:index:Role": "Role"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-iam",
  "token": "pulumi:providers:aws-iam",
  "fqn": "pulumi_aws_iam",
  "class": "Provider"
 }
]
"""
)
