// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface PolicyStatementArgs {
    actions?: pulumi.Input<pulumi.Input<string>[]>;
    conditions?: pulumi.Input<string>;
    effect?: pulumi.Input<string>;
    resources?: pulumi.Input<pulumi.Input<string>[]>;
    sid?: pulumi.Input<string>;
}
